### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by neonailol** [Thogor/CheckMate#6]
Are there easy way to adapt this plugin to support finding unchecked exceptions in kotlin?

**Comment by ThomasGoris** [comment]
I will see if this is possible. 
It will take some time as I have no experience in Kotlin or its plugin development. 
If someone with more experience in Kotlin would like to contribute I'd be happy to approve a pull request.

**Comment by neonailol** [comment]
I am actually looking into this, and main problem that i found, is that kotlin function calls are not PsiStatement, and all code in this plugin are build around PsiStatement, they are KtCallElement or KtCallableDeclaration, did not quite figured it yet

**Comment by ThomasGoris** [comment]
I've been trying to find the KtCallElement and KtCallableDeclaration classes but I can't seem to find them on the class path. 

The ExceptionDiscoveringVisitor extends the JavaRecursiveElementVisitor class. I can't seem to find an equivalant for Kotlin. If the KtCallElement and KtCallableDeclaration classes are subclasses of PsiCallExpression we would only need to tweak the visitCallExpression method to also visit Kotlin calls.

**Comment by ThomasGoris** [comment]
It seems that KtCallElement/KtCallableDeclaration aren't subclasses of PsiCallExpression.

**Comment by neonailol** [comment]
did you add <depends>org.jetbrains.kotlin</depends> to project?
and all psi classes can be found on github for example https://github.com/JetBrains/kotlin/tree/master/compiler/frontend/src/org/jetbrains/kotlin/psi

**Comment by ThomasGoris** [comment]
No I haven't, thx for the help.
I'll look into it ASAP.

**Comment by Thogor** [comment]
Completely forgot about this. 
Including Kotlin support would take a lot of time that I don't have right now. 

Sorry for the late response.
